### ISSUE TITLE
http daemon integration?

### ISSUE THREAD

**Issue by AstraLuma** [AdvocatesInc/django-channels-discord#1]
Feature request: Being able to run the discord connections from the same process as the one processing http requests. (ie, daphne/hypercorn/uvicorn)

This would simplify deployment to eg heroku because you'd only have to run one daemon instead of two.

**Comment by AstraLuma** [comment]
actually, nvm, with `discord.py` being put to pasture, this library seems... ill-advised.

**Comment by MattBroach** [comment]
FWIW, I've replaced `discord.py` with one of the currently maintained forks ([pycord](https://github.com/Pycord-Development/pycord)), and will continue to monitor to see which fork eventually stabilizes as the primary `discord.py` replacement.

That said, I think it would be hard to do this integration without also forking daphne (or one of the alternatives) and essentially combining libraries.  It _may_ be possible to import the `ChannelsDiscordClient` and hijack the django init process to start up the client manually, but that's probably somewhat out of the scope of this project.

**Comment by AstraLuma** [comment]
I ended up writing my own framework, and I tie the gateway worker task to [lifespan](https://asgi.readthedocs.io/en/latest/specs/lifespan.html)

This means that Daphne is the only ASGI httpd _not_ supported.
